[sonarqube] Docker images updates - 2021-07-19
GoogleCloudPlatform/sonarqube-docker pull request #44
Opened 2021-07-19 14:15 UTC by EugeneKorolevich

2021-07-20 12:07 UTC, armandomiani requested changes

2021-07-20 12:07 UTC, armandomiani commented on versions.yaml
> +- dir: 7/debian10/7.9
You can remove 7.9 version.

2021-07-21 08:41 UTC, EugeneKorolevich commented on versions.yaml
> +- dir: 7/debian10/7.9
Deleted 7 folder and version

2021-07-26 08:59 UTC, armandomiani approved these changes

2021-07-26 08:59 UTC, merged